package com.chatbot.agent.service.tools;

import com.chatbot.agent.config.ToolExecutionProperties;
import com.chatbot.agent.model.ToolModel;
import com.fasterxml.jackson.databind.ObjectMapper;
import lombok.extern.slf4j.Slf4j;
import org.slf4j.MDC;
import org.springframework.stereotype.Component;

import java.util.Map;

/**
 * PythonScriptBuilder - Builds Python scripts with eztool & ezLog injection
 *
 * Generates complete Python script including:
 *  - eztool() function for inter-tool communication
 *  - ezLog() function for structured contextual logging
 *  - ezMain() entry point wrapper
 *  - Parameter injection
 *  - Protocol implementation
 *  - Safe imports
 */
@Slf4j
@Component
public class PythonScriptBuilder {

    private final ToolExecutionProperties config;
    private final ObjectMapper jsonMapper;

    public PythonScriptBuilder(ToolExecutionProperties config, ObjectMapper jsonMapper) {
        this.config = config;
        this.jsonMapper = jsonMapper;
    }

    /**
     * Build complete Python script with eztool + ezLog support
     *
     * @param context Execution context
     * @param tool    The tool to execute
     * @param params  Parameters to pass
     * @return Complete Python script
     */
    public String buildScript(ExecutionContext context, ToolModel.Tool tool, Map<String, Object> params) {
        StringBuilder script = new StringBuilder();

        // 1. Add header comment
        script.append("#!/usr/bin/env python3\n");
        script.append("# Auto-generated script for tool: ").append(tool.getFuncNameKey()).append("\n");
        script.append("# ExecutionId: ").append(context.getExecutionId()).append("\n");
        script.append("# DO NOT EDIT - Generated by ToolExecutionService\n\n");

        // 2. Add safe imports
        script.append(buildImports());

        // 3. Inject runtime context (__ez_context__)
        script.append(buildContextInjection(context, tool));

        // 4. Add ezLog() function
        script.append(buildEzLogFunction());

        // 5. Add eztool() function
        script.append(buildEzToolFunction());

        // 6. Inject parameters as global variables
        script.append(buildParameterInjection(params));

        // 7. Add user's code wrapped in ezMain
        script.append(buildUserCode(tool.getPythonCode()));

        // 8. Add main execution block
        script.append(buildMainExecution());

        log.debug("[executionId={}] Built Python script ({} bytes)",
                context.getExecutionId(), script.length());

        return script.toString();
    }

    /**
     * Build import statements
     */
    private String buildImports() {
        StringBuilder imports = new StringBuilder();

        imports.append("# === Safe Imports ===\n");
        imports.append("import sys\n");
        imports.append("import json\n");
        imports.append("import uuid\n");
        imports.append("import datetime\n");

        for (String module : config.getPython().getAllowedModules()) {
            imports.append("import ").append(module).append("\n");
        }
        imports.append("\n");

        return imports.toString();
    }

    /**
     * Inject execution context (__ez_context__)
     */
    private String buildContextInjection(ExecutionContext context, ToolModel.Tool tool) {
        try {
            String contextJson = jsonMapper.writeValueAsString(Map.of(
                    "requestId", MDC.get("requestId"),
                    "executionId", context.getExecutionId(),
                    "toolId", tool.getFuncNameKey()
            ));

            return "# === Execution Context ===\n" +
                    "__ez_context__ = json.loads('" + escapePythonString(contextJson) + "')\n\n";
        } catch (Exception e) {
            log.error("Failed to build context JSON", e);
            return "__ez_context__ = {}\n\n";
        }
    }

    /**
     * Build ezLog() helper for structured contextual logging
     */
    private String buildEzLogFunction() {
        return """
                # === EzLog Function ===
                def ezLog(message, data=None, level="info"):
                    try:
                        log_entry = {
                            "type": "log",
                            "timestamp": datetime.datetime.utcnow().isoformat() + "Z",
                            "context": __ez_context__,
                            "level": level,
                            "message": str(message),
                            "data": data
                        }
                        sys.stdout.write(json.dumps(log_entry, default=str, ensure_ascii=False) + "\\n")
                        sys.stdout.flush()
                    except Exception as e:
                        sys.stdout.write(json.dumps({
                            "type": "log",
                            "level": "error",
                            "message": f"ezLog failed: {str(e)}",
                            "data": None
                        }) + "\\n")
                        sys.stdout.flush()
                        
                """;
    }

    /**
     * Build eztool() function for inter-tool communication
     */
    private String buildEzToolFunction() {
        String requestMarker = config.getPython().getProtocol().getRequestMarker();
        String requestEndMarker = config.getPython().getProtocol().getRequestEndMarker();
        String responseMarker = config.getPython().getProtocol().getResponseMarker();
        String responseEndMarker = config.getPython().getProtocol().getResponseEndMarker();

        return String.format("""
                # === EzTool Function ===
                def eztool(tool_id, params=None):
                    \"\"\"
                    Call another tool from Python
                    \"\"\"
                    if params is None:
                        params = {}
                    call_id = str(uuid.uuid4())
                    request = {
                        "type": "TOOL_CALL",
                        "toolId": tool_id,
                        "params": params,
                        "callId": call_id
                    }
                    print("%s", flush=True)
                    print(json.dumps(request), flush=True)
                    print("%s", flush=True)
                    try:
                        response_marker = sys.stdin.readline().strip()
                        if response_marker != "%s":
                            raise RuntimeError(f"Protocol error: expected response marker, got: {response_marker}")
                        response_json = sys.stdin.readline().strip()
                        end_marker = sys.stdin.readline().strip()
                        if end_marker != "%s":
                            raise RuntimeError(f"Protocol error: expected end marker, got: {end_marker}")
                        response = json.loads(response_json)
                        if response.get("success"):
                            return response.get("data")
                        else:
                            error_msg = response.get("error", "Unknown error")
                            error_code = response.get("errorCode", "UNKNOWN")
                            raise RuntimeError(f"Tool '{tool_id}' failed [{error_code}]: {error_msg}")
                    except json.JSONDecodeError as e:
                        raise RuntimeError(f"Failed to parse response from tool '{tool_id}': {e}")
                    except Exception as e:
                        raise RuntimeError(f"Error calling tool '{tool_id}': {e}")
                """, requestMarker, requestEndMarker, responseMarker, responseEndMarker);
    }

    /**
     * Build parameter injection code
     */
    private String buildParameterInjection(Map<String, Object> params) {
        if (params == null || params.isEmpty()) {
            return "# === No parameters ===\n\n";
        }

        StringBuilder injection = new StringBuilder();
        injection.append("# === Injected Parameters ===\n");

        for (Map.Entry<String, Object> entry : params.entrySet()) {
            String key = entry.getKey();
            Object value = entry.getValue();

            if (isValidPythonIdentifier(key)) {
                injection.append(key).append(" = ");
                injection.append(convertToPythonLiteral(value));
                injection.append("\n");
            } else {
                log.warn("Skipping parameter with invalid Python identifier: {}", key);
            }
        }
        injection.append("\n");

        return injection.toString();
    }

    /**
     * Build user code with ezMain wrapper
     */
    private String buildUserCode(String userCode) {
        StringBuilder code = new StringBuilder();
        code.append("# === User Code ===\n");

        if (userCode.contains("def ezMain(")) {
            code.append(userCode).append("\n\n");
        } else {
            code.append("def ezMain(data):\n")
                    .append("    \"\"\"User-defined tool logic\"\"\"\n");
            for (String line : userCode.split("\n")) {
                code.append("    ").append(line).append("\n");
            }
            code.append("\n");
        }
        return code.toString();
    }

    /**
     * Build main execution block
     */
    private String buildMainExecution() {
        String resultMarker = config.getPython().getProtocol().getResultMarker();
        return String.format("""
                # === Main Execution ===
                if __name__ == "__main__":
                    try:
                        data = {}
                        for var_name, var_value in list(globals().items()):
                            if not var_name.startswith('_') and var_name not in ['sys', 'json', 'uuid', 'datetime', 'math', 're', 'statistics', 'eztool', 'ezMain', 'data']:
                                data[var_name] = var_value
                        ezLog("Starting execution", data)
                        result = ezMain(data)
                        ezLog("Execution completed", result)
                        print("%s", flush=True)
                        print(json.dumps({"success": True, "data": result}), flush=True)
                    except Exception as e:
                        ezLog("Execution failed", {"error": str(e), "type": type(e).__name__}, "error")
                        print("%s", flush=True)
                        print(json.dumps({"success": False, "error": str(e), "type": type(e).__name__}), flush=True)
                        sys.exit(1)
                """, resultMarker, resultMarker);
    }

    /**
     * Validate Python identifiers
     */
    private boolean isValidPythonIdentifier(String name) {
        if (name == null || name.isEmpty()) return false;
        if (!Character.isLetter(name.charAt(0)) && name.charAt(0) != '_') return false;
        for (int i = 1; i < name.length(); i++) {
            char c = name.charAt(i);
            if (!Character.isLetterOrDigit(c) && c != '_') return false;
        }
        String[] keywords = {"False","None","True","and","as","assert","async","await","break","class",
                "continue","def","del","elif","else","except","finally","for","from","global","if","import",
                "in","is","lambda","nonlocal","not","or","pass","raise","return","try","while","with","yield"};
        for (String kw : keywords) if (name.equals(kw)) return false;
        return true;
    }

    /**
     * Convert Java value to Python literal
     */
    private String convertToPythonLiteral(Object value) {
        if (value == null) return "None";
        if (value instanceof String) return "\"" + escapePythonString((String) value) + "\"";
        if (value instanceof Number) return value.toString();
        if (value instanceof Boolean) return ((Boolean) value) ? "True" : "False";
        try {
            String json = jsonMapper.writeValueAsString(value);
            return "json.loads('" + escapePythonString(json) + "')";
        } catch (Exception e) {
            log.error("Error converting to Python literal", e);
            return "None";
        }
    }

    /**
     * Escape special characters in Python string
     */
    private String escapePythonString(String str) {
        return str.replace("\\", "\\\\")
                .replace("\"", "\\\"")
                .replace("\n", "\\n")
                .replace("\r", "\\r")
                .replace("\t", "\\t")
                .replace("'", "\\'");
    }
}