package com.chatbot.agent.service.tools;

import com.chatbot.agent.config.ToolExecutionProperties;
import com.chatbot.agent.model.ToolModel;
import com.fasterxml.jackson.databind.ObjectMapper;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Component;

import java.util.Map;

/**
 * PythonScriptBuilder - Builds Python scripts with eztool injection
 * <p>
 * Generates complete Python script including:
 * - eztool() function for inter-tool communication
 * - ezMain() entry point wrapper
 * - Parameter injection
 * - Protocol implementation
 * - Safe imports
 */
@Slf4j
@Component
public class PythonScriptBuilder {

    private final ToolExecutionProperties config;
    private final ObjectMapper jsonMapper;

    public PythonScriptBuilder(ToolExecutionProperties config, ObjectMapper jsonMapper) {
        this.config = config;
        this.jsonMapper = jsonMapper;
    }

    /**
     * Build complete Python script with eztool support
     *
     * @param context Execution context
     * @param tool    The tool to execute
     * @param params  Parameters to pass
     * @return Complete Python script
     */
    public String buildScript(ExecutionContext context, ToolModel.Tool tool, Map<String, Object> params) {
        StringBuilder script = new StringBuilder();

        // 1. Add header comment
        script.append("#!/usr/bin/env python3\n");
        script.append("# Auto-generated script for tool: ").append(tool.getFuncNameKey()).append("\n");
        script.append("# ExecutionId: ").append(context.getExecutionId()).append("\n");
        script.append("# DO NOT EDIT - Generated by ToolExecutionService\n\n");

        // 2. Add safe imports
        script.append(buildImports());

        // 3. Add eztool function
        script.append(buildEzToolFunction());

        // 4. Inject parameters as global variables
        script.append(buildParameterInjection(params));

        // 5. Add user's code wrapped in ezMain
        script.append(buildUserCode(tool.getPythonCode()));

        // 6. Add main execution block
        script.append(buildMainExecution());

        log.debug("[executionId={}] Built Python script ({} bytes)",
                context.getExecutionId(), script.length());

        return script.toString();
    }

    /**
     * Build import statements
     */
    private String buildImports() {
        StringBuilder imports = new StringBuilder();

        imports.append("# === Safe Imports ===\n");
        imports.append("import sys\n");
        imports.append("import json\n");
        imports.append("import uuid\n");

        // Add configured allowed modules
        for (String module : config.getPython().getAllowedModules()) {
            imports.append("import ").append(module).append("\n");
        }

        imports.append("\n");

        return imports.toString();
    }

    /**
     * Build eztool function for inter-tool communication
     */
    private String buildEzToolFunction() {
        String requestMarker = config.getPython().getProtocol().getRequestMarker();
        String requestEndMarker = config.getPython().getProtocol().getRequestEndMarker();
        String responseMarker = config.getPython().getProtocol().getResponseMarker();
        String responseEndMarker = config.getPython().getProtocol().getResponseEndMarker();

        return String.format("""
                # === EzTool Function ===
                def eztool(tool_id, params=None):
                    \"\"\"
                    Call another tool from Python
                
                    Args:
                        tool_id (str): The ID of the tool to call
                        params (dict, optional): Parameters to pass to the tool
                
                    Returns:
                        dict: Result from the tool execution
                
                    Raises:
                        RuntimeError: If tool execution fails
                    \"\"\"
                    if params is None:
                        params = {}
                
                    # Generate unique call ID
                    call_id = str(uuid.uuid4())
                
                    # Create request message
                    request = {
                        "type": "TOOL_CALL",
                        "toolId": tool_id,
                        "params": params,
                        "callId": call_id
                    }
                
                    # Send request to Java via stdout
                    print("%s", flush=True)
                    print(json.dumps(request), flush=True)
                    print("%s", flush=True)
                
                    # Wait for response from Java via stdin
                    try:
                        response_marker = sys.stdin.readline().strip()
                        if response_marker != "%s":
                            raise RuntimeError(f"Protocol error: expected response marker, got: {response_marker}")
                
                        response_json = sys.stdin.readline().strip()
                
                        end_marker = sys.stdin.readline().strip()
                        if end_marker != "%s":
                            raise RuntimeError(f"Protocol error: expected end marker, got: {end_marker}")
                
                        # Parse response
                        response = json.loads(response_json)
                
                        if response.get("success"):
                            return response.get("data")
                        else:
                            error_msg = response.get("error", "Unknown error")
                            error_code = response.get("errorCode", "UNKNOWN")
                            raise RuntimeError(f"Tool '{tool_id}' failed [{error_code}]: {error_msg}")
                
                    except json.JSONDecodeError as e:
                        raise RuntimeError(f"Failed to parse response from tool '{tool_id}': {e}")
                    except Exception as e:
                        raise RuntimeError(f"Error calling tool '{tool_id}': {e}")
                
                """, requestMarker, requestEndMarker, responseMarker, responseEndMarker);
    }

    /**
     * Build parameter injection code
     */
    private String buildParameterInjection(Map<String, Object> params) {
        if (params == null || params.isEmpty()) {
            return "# === No parameters ===\n\n";
        }

        StringBuilder injection = new StringBuilder();
        injection.append("# === Injected Parameters ===\n");

        for (Map.Entry<String, Object> entry : params.entrySet()) {
            String key = entry.getKey();
            Object value = entry.getValue();

            if (isValidPythonIdentifier(key)) {
                injection.append(key).append(" = ");
                injection.append(convertToPythonLiteral(value));
                injection.append("\n");
            } else {
                log.warn("Skipping parameter with invalid Python identifier: {}", key);
            }
        }

        injection.append("\n");

        return injection.toString();
    }

    /**
     * Build user code with ezMain wrapper
     */
    private String buildUserCode(String userCode) {
        StringBuilder code = new StringBuilder();

        code.append("# === User Code ===\n");

        // Check if user already defined ezMain
        if (userCode.contains("def ezMain(")) {
            // User provided ezMain - use as is
            code.append(userCode);
            code.append("\n\n");
        } else {
            // Wrap user code in ezMain
            code.append("def ezMain(data):\n");
            code.append("    \"\"\"\n");
            code.append("    User-defined tool logic\n");
            code.append("    \"\"\"\n");

            // Indent user code
            String[] lines = userCode.split("\n");
            for (String line : lines) {
                code.append("    ").append(line).append("\n");
            }

            code.append("\n");
        }

        return code.toString();
    }

    /**
     * Build main execution block
     */
    private String buildMainExecution() {
        String resultMarker = config.getPython().getProtocol().getResultMarker();

        return String.format("""
                # === Main Execution ===
                if __name__ == "__main__":
                    try:
                        # Prepare data dict from injected parameters
                        data = {}
                        for var_name, var_value in list(globals().items()):
                            if not var_name.startswith('_') and var_name not in ['sys', 'json', 'uuid', 'math', 'datetime', 're', 'statistics', 'eztool', 'ezMain', 'data']:
                                data[var_name] = var_value
                
                        # Execute user code
                        result = ezMain(data)
                
                        # Output result with marker
                        print("%s", flush=True)
                        print(json.dumps({"success": True, "data": result}), flush=True)
                
                    except Exception as e:
                        # Output error with marker
                        print("%s", flush=True)
                        print(json.dumps({"success": False, "error": str(e), "type": type(e).__name__}), flush=True)
                        sys.exit(1)
                """, resultMarker, resultMarker);
    }

    /**
     * Check if string is valid Python identifier
     */
    private boolean isValidPythonIdentifier(String name) {
        if (name == null || name.isEmpty()) {
            return false;
        }

        // Must start with letter or underscore
        if (!Character.isLetter(name.charAt(0)) && name.charAt(0) != '_') {
            return false;
        }

        // Rest must be letters, digits, or underscores
        for (int i = 1; i < name.length(); i++) {
            char c = name.charAt(i);
            if (!Character.isLetterOrDigit(c) && c != '_') {
                return false;
            }
        }

        // Check against Python keywords
        String[] pythonKeywords = {
                "False", "None", "True", "and", "as", "assert", "async", "await",
                "break", "class", "continue", "def", "del", "elif", "else", "except",
                "finally", "for", "from", "global", "if", "import", "in", "is",
                "lambda", "nonlocal", "not", "or", "pass", "raise", "return",
                "try", "while", "with", "yield"
        };

        for (String keyword : pythonKeywords) {
            if (name.equals(keyword)) {
                return false;
            }
        }

        return true;
    }

    /**
     * Convert Java value to Python literal
     */
    private String convertToPythonLiteral(Object value) {
        if (value == null) {
            return "None";
        } else if (value instanceof String) {
            return "\"" + escapePythonString((String) value) + "\"";
        } else if (value instanceof Number) {
            return value.toString();
        } else if (value instanceof Boolean) {
            return (Boolean) value ? "True" : "False";
        } else {
            // Complex types - convert to JSON
            try {
                String json = jsonMapper.writeValueAsString(value);
                return "json.loads('" + escapePythonString(json) + "')";
            } catch (Exception e) {
                log.error("Error converting value to Python literal", e);
                return "None";
            }
        }
    }

    /**
     * Escape special characters in Python string
     */
    private String escapePythonString(String str) {
        return str.replace("\\", "\\\\")
                .replace("\"", "\\\"")
                .replace("\n", "\\n")
                .replace("\r", "\\r")
                .replace("\t", "\\t")
                .replace("'", "\\'");
    }
}
